jlfwong/speedscope

- flamechart-view.tsx
As discussed: double clicking a node will position that node at the top left of the view, and resize horizontally to fit that node.
becomes
> Focus frames beneath a node on dblclick

- README.md
- application.tsx
- hash-params.ts
On init, we check the hash fragment for these parameters and load the URL. We
always show a loading state in that case rather than the landing screen.
When determining the title, an explicitly-specified title takes precedence,
otherwise we use the filename.
I also added an error state, currently only used for my new code, but possibly
there could be a more robust or widespread error handling approach in the
future.
> Add profileURL and title hash parameters

- application.tsx
- color.ts
- flamechart-style.ts
- flamechart-view.tsx
- style.ts
This introduces a view for showing detailed information about a selected frame in the flamegraph. This provides information about self time & aggregate times across all instances of the function, regardless of where it is in the flamegraph.
This also shows a full stack with file & line information.
Fixes #20
> Add a detail view to view aggregate statistics & file details

- deploy.sh
We previously had to serve from `/speedscope/` because the website was https://jlfwong.github.io/speedscope/. Now that we're going to serve from https://www.speedscope.app, we no longer have to do that (in fact it's important that we don't do that).
> Change the public asset directory to be top level now that we have a domain

- flamechart-style.ts
- flamechart-view.tsx
- import/instruments.ts
- profile.ts
This contains 2 fixes for the details view
The first is that the padding in the scrolling view was causing the last frame to be clipped
The second is that we were uselessly displaying "(speedscope root)" in the stack trace view.
This also removes some sketch specific stuff from the keyed archive expanding code
Fixes #32
> Fixes for details view

- flamechart-view.tsx
This makes scrolling feel much zippier in Firefox
Fixes #46
> Take`WheelEvent.deltaMode` into account when calculating scroll amounts

- import/instruments.ts
- sample/profiles/Instruments/8.3.3/integer-uniquer-data.grammar
- sample/profiles/Instruments/8.3.3/integer-uniquer-index.grammar
I knew early on that `integeruniquer.index` could be used to index into `integeruniquer.data`, but I initially thought it was an optimization rather than a necessity. It seems like if there's data past the 1MB threshold in `integeruniquer.data`, then `integeruniquer.index` is actually quite useful.
The file seems to contain `[byte offset, MB offset]` pairs encoded as two 32 bit unsigned little endian integers. Using that to decode the integer arrays encoded in `integeruniquer.data` allows the file in #63 to load.
Fixes #63
> Update instruments import to use integeruniquer.index file

- .vscode/settings.json
- application.tsx
- flamechart-renderer.ts
- flamechart.ts
- profile.test.ts
- profile.ts
- row-atlas.ts
- sample/profiles/stackcollapse/recursion.txt
- test-utils.ts
- utils.test.ts
- utils.ts
This makes the left-heavy view much more useful since recursive calls are all collapsed together.
Press `r` to activate
Fixes #37
> Add a hotkey to flatten recursion

- flamechart-view.tsx
> Extend scroll height of flamechart to prevent details view from covering flamechart

- application.tsx
- import/chrome.ts
- import/index.ts
- profile.ts
I'm not sure why this happens, but I have multiple profiles coming from Chrome that have negative values in the exported `timeDelta` objects.
This PR also cleans up some of the error reporting logic to hopefully stop logging `undefined` to the console on import failure.
Fixes #70
> Fix negative import timeDeltas between samples in Chrome

- flamechart-view.tsx
- math.ts
- sandwich-view.tsx
The problem was that the calculation of the origin bounds was done before clamping the viewport rect size
> Prevent zooming from moving viewport rect out of bounds

- application.tsx
- deploy.sh
This makes it easier to download speedscope to run totally offline, and makes embedding it into other applications easier since it no longer depends on specific URL paths.
> Make speedscope work when hosted on an arbitrary URL or served from file://

- application.tsx
- flamechart-minimap-view.tsx
- profile-table-view.tsx
- style.ts
- Move the help button to the right side of the toolbar
- Remove the pointer cursor from buttons (https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)
- Add subtle hover transition animations for tabs & big browse button
> Design tweaks

- test-utils.ts
When importing files, there are two different paths we use for determining the file format.
The first is to pattern match on the filename.
If that fails, we fall back to examining the structure of the file, which can be slower and therefore wasteful.
Before this PR, we only tests that the filename pattern matching was correctly identifying the format. This PR ensures that our file structure matching is working correctly too.
> Add tests ensuring that import still works even for unfamiliar filenames

- README.md
- cli.js
Test Plan:
- `./cli.js` opens speedscope in browser with no file selected
- `./cli.js sample/profiles/Chrome/65/simple-timeline.json` opens profile
- `cat sample/profiles/Chrome/65/simple-timeline.json | ./cli.js -` opens profile
- `node --prof-process --preprocess -j sample/profiles/node/8.5.0/isolate-0x102802600-v8.log | ./cli.js -` opens profile
Fixes #95
> Optionally read from stdin via cli

- src/views/flamechart-minimap-view.tsx
- src/views/flamechart-pan-zoom-view.tsx
- src/views/flamechart-view.tsx
- src/views/flamechart-wrapper.tsx
The problem was that the viewport size was dependent on `overlayCanvas.width` and `overlayCanvas.height`, both of which were being set *after* the initial rectangle rendering. The fix is to just do the canvas resizing before the rectangle rendering.
Fixes #114
> Fix use of incorrect viewport size

- src/lib/flamechart.ts
- src/views/flamechart-view.tsx
- src/views/flamechart-wrapper.tsx
Test Plan:
Copy and paste the following into speedscope, then zoom in as far as you can into the right side of the profile.
```
a 1
b 100000000000000000000
```
Before this PR, it would hang. After this PR, it caps the zoom and doesn't hang. The cap of the zoom still allows you to zoom in really, really far.
Fixed #61
> Clamp zoom to prevent floating point issues

- src/views/flamechart-pan-zoom-view.tsx
This prevents dragging on the canvas from changing the selection
Fixes #94
> Ignore click event following a drag

- src/lib/emscripten.test.ts
- src/lib/emscripten.ts
Apparently emscripten symbols are allowed to contain dashes?
e.g. here's a line from a mapping that failed to import before this PR: `527:i32s-div`
> Support emscripten symbols containing dashes

- src/lib/typed-redux.ts
- src/lib/utils.test.ts
- src/lib/utils.ts
- src/store/actions.ts
- src/store/flamechart-view-state.test.ts
- src/store/getters.ts
- src/store/index.test.ts
- src/store/index.ts
- src/store/profiles-state.test.ts
- src/store/profiles-state.ts
- src/store/sandwich-view-state.test.ts
- src/store/sandwich-view-state.ts
- src/store/store-test-utils.ts
- src/views/application.tsx
- src/views/profile-table-view.tsx
This adds some baseline tests for the redux store, and also fixes some bugs I found along the way.
Bugs fixed:
- Changing selection after something has been selected within the sandwich view now works
- Table sort state is now preserved when switching between profiles
Fixes #124
> Add tests for redux store

- src/views/flamechart-pan-zoom-view.tsx
> Fix text culling of ellipses along the left side of the viewport

- src/views/application.tsx
The problem was that I was using `canvas.getBoundingClientRect()` to get the size to resize to, but that was changing as the result of CSS properties set on the canvas! Instead, we take the measurements of its container now which is set to fill the screen, and the canvas has its size entirely managed by `graphics.ts`.
> Fix a regression in resize behavior from #147

- src/lib/value-formatters.test.ts
- src/lib/value-formatters.ts
Hi @jlfwong, I made changes to `TimeFormatter` to fix #90. Now it should render `1:30min` instead of `1.50min` 
However, I am not very proficient in Typescript and I did an ugly workaround. Maybe you can suggest something more elegant?
> Change time formatting for minutes from 1.50min to 1:30

- sample/profiles/stackcollapse/simple-crlf.txt
- src/import/__snapshots__/bg-flamegraph.test.ts.snap
- src/import/bg-flamegraph.test.ts
- src/import/index.ts
This fixes #152, in that it allows "collapsed stacks" files generated with
tools using Windows line endings to be imported into the tool verbatim.
> Allow optional CR before LF when probing collapsed stacks files

- src/views/flamechart-pan-zoom-view.tsx
Instead of using `key`, use `code` which according to [this](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) should work consistently for different layouts.
I tested the modification on a french AZERTY keyboard and it works fine.
> Make the wasd keymappings work on azerty keyboards

- src/import/utils.ts
#165 introduced a performance regression by using a really inefficient method for converting from array buffers into string. This should ix it by using `TextDecoder` instead.
> Use TextDecoder if available for converting from an ArrayBuffer for speed

- sample/profiles/trace-event/multiprocess.json
- sample/profiles/trace-event/simple-object.json
- sample/profiles/trace-event/simple.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/index.ts
- src/import/trace-event.test.ts
- src/import/trace-event.ts
This PR implements basic import of profiles from the "Trace Event Format", which is used by `chrome://tracing`, but also which many other tools target as a convenient event tracing format. The spec can be found here: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.xqopa5m0e28f.
The standard supports a broad set of events, some of which don't yet have any practical way to visualize them in speedscope. This PR implements support for the `B`, `E`, and `X` events, as well as gathering process and thread names via some of the `M` events.
This work was motivated by a generous donation to /dev/color by @aras-p: https://github.com/jlfwong/speedscope/issues/77#issuecomment-455077014
Fixes #77
> Support basic import of profiles in the "Trace Event Format"

- sample/profiles/trace-event/multiprocess.json
- src/import/trace-event.ts
The spec for the Trace Event Format technically requires that all entries have "ts" values, and they do in the profiles recorded using chrome://tracing. We don't actually use those values in the case of "M" (metadata) events, however, and they're semantically meaningless as far as I can tell, so let's stop requiring them.
This allows the files that @aras-p provided in #77 to import successfully.
Fixes #77
> Fix importing of Trace Event Format files with no ts field on M events

- package.json
- sample/profiles/trace-event/simple-object-partial.json
- sample/profiles/trace-event/simple-partial.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/index.ts
- src/import/partial-json-parser.d.ts
- src/import/trace-event.test.ts
- src/import/trace-event.ts
Partial files are allowed in many specs, e.g. Trace Event Format,
so the viewer should be able to load partial files as well.
> Support importing partial JSON files

- sample/profiles/trace-event/simple-partial-trailing-comma.json
- sample/profiles/trace-event/simple-partial-whitespace.json
- sample/profiles/trace-event/simple-partial.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/index.ts
- src/import/trace-event.test.ts
- src/import/trace-event.ts
This PR introduces support for importing JSON based profiles that are missing a terminating `]` (and possibly have an extraneous `,`).
This is similar to #202, but takes a much more targeted and simple approach.
I'm confident that this approach is sufficient because this is exactly what `chrome://tracing` does: https://github.com/catapult-project/catapult/blob/27e047e0494df162022be6aa8a8862742a270232/tracing/tracing/extras/importer/trace_event_importer.html#L197-L208
Fixes #204
> Support importing unterminated JSON in simple cases

- sample/profiles/trace-event/must-retain-original-order.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
The code to import trace formatted events intentionally re-orders events in order to make it easier at flamegraph construction time to order the pushes and pops of frames.
It turns out that this re-ordering results in incorrect flamegraphs being generated as shown in #251.
This PR fixes this by avoiding re-ordering in situations where it isn't necessary.
> Trace event: Prevent event re-ordering from generating incorrect flamegraphs

- sample/profiles/speedscope/invalid/incomplete-trace.json
- sample/profiles/speedscope/invalid/out-of-order-events.json
- src/lib/__snapshots__/file-format.test.ts.snap
- src/lib/file-format.test.ts
- src/lib/profile.ts
- src/lib/test-utils.ts
Before this change, profiles like those in #272 would import but would display misleading data. Let's fail hard instead.
Fixes #272
> Fail loudly when profile is imported with unmatched open/close events

- package-lock.json
- package.json
- scripts/ci.sh
- scripts/generate-file-format-schema-json.js
Fixes #268 
I fixed it by dropping the dependency on quicktype entirely, and using its dependency directly. I still don't understand why the version of typescript used in this repository affects what quicktype is doing, but it seems like the issue is in quicktype, not its dependency.
I validated this change was correct by diffing the output of `node scripts/generate-file-format-schema-json.js` with what's currently on http://speedscope.app/file-format-schema.json. There's no difference.
This PR also includes changes to the CI script to ensure that we can catch this before hitting master next time.
> Fix schema generation in new TypeScript version

- src/lib/preact-redux.tsx
To test this, load a profile, then save a `.tsx` file locally. Before this change, it would bring you back to the welcome screen after hot reload. After this change, application state is still displayed. This is because before the change, the `setGLCanvas` action wasn't resulting in a re-render because it occurred between the initial render and the `useLayoutEffect` callback.
Fixes #276
> Fix hot module reload issues caused by subtle bug in useSelector

- .eslintrc.js
- src/lib/preact-redux.tsx
- src/store/index.ts
- src/views/application-container.tsx
- src/views/callee-flamegraph-view.tsx
- src/views/flamechart-view-container.tsx
- src/views/inverted-caller-flamegraph-view.tsx
- src/views/profile-table-view.tsx
Profile switching was subtly broken because action creators weren't being correctly re-bound due to a missing dependency in a `useCallback` call.
I also tried to reduce boilerplate in this PR by adding additional exhaustive deps protection via eslint for `useSelector`, `useAppSelector`, and `useActionCreator`. The removes the need for using `useCallback` or each of those.
Fixes #280
> Fix bug with bad caching of action creators

- README.md
- src/lib/fuzzy-find.test.ts
- src/lib/fuzzy-find.ts
- src/views/profile-select.tsx
- src/views/style.ts
- src/views/toolbar.tsx
This adds much better UI for selecting different profiles within a single import.
You can now hover over the middle of the toolbar or hit `t` on your keyboard to bring up the profile selector. From there, you can use fuzzy-find to switch to the profile you want, and hit "enter" to select it. The up and down arrow keys can be used while the profile selector filter input is focused to move through the list of profiles.
I think the "next" and "prev" buttons are now totally useless, so I removed them.
Fixes #167
> Introduce a profile selector dropdown

- src/store/getters.ts
- src/views/flamechart-pan-zoom-view.tsx
- src/views/flamechart-view.tsx
- src/views/flamechart-wrapper.tsx
- src/views/inverted-caller-flamegraph-view.tsx
This fixes two unrelated problems which together caused performance issues in the sandwich view & made hover tooltips appear to be broken.
The first issue was caused by continuously priming the `requestAnimationFrame` loop when it should be a no-op, and the second issue was caused by using different cache keys when trying to access a memoized value in the caller & callee flamegraph components. This resulted in thrash, and especially bad performance because the cache miss was resulting in us re-allocating the WebGL framebuffer on every frame, which is unsurprisingly quite slow.
Fixes #212 
Fixes #155 
Fixes #74 (though this was maybe already fixed)
> Fix performance issues for the caller/callee flamegraphs in the sandwich view

- src/lib/text-utils.test.ts
- src/lib/text-utils.ts
- src/views/callee-flamegraph-view.tsx
- src/views/flamechart-pan-zoom-view.tsx
- src/views/flamechart-view-container.tsx
- src/views/flamechart-view.tsx
- src/views/flamechart-wrapper.tsx
- src/views/inverted-caller-flamegraph-view.tsx
- src/views/profile-table-view.tsx
- src/views/scrollable-list-view.tsx
- src/views/search-view.tsx
- src/views/style.ts
This implements the next step towards full featured search in speedscope: visual highlighting of matching search results in the time ordered & left heavy views. This doesn't yet add the ability to click prev/next to select the next matching element in the editor, but I'm still planning on doing something like that. I haven't figured out yet what I want the user experience to be like for that.
This works towards fixing #38
> Implement search highlighting in time order & left heavy views

- src/views/flamechart-pan-zoom-view.tsx
Before:
After:
Works towards #38
> Increase contrast for flamechart search results by fading text for unmatched frames

- README.md
The Austin format conversion tools have been moved to the dedicated austin-python module. The README has been updated to point to the new instructions.
> Update link to Austin instructions

- sample/profiles/trace-event/end-event-with-empty-stack.json
- sample/profiles/trace-event/end-non-top-of-stack.json
- sample/profiles/trace-event/mismatched-args.json
- sample/profiles/trace-event/mismatched-name.json
- sample/profiles/trace-event/not-enough-end-events.json
- sample/profiles/trace-event/only-begin-events.json
- sample/profiles/trace-event/out-of-order-unbalanced-name.json
- sample/profiles/trace-event/out-of-order.json
- sample/profiles/trace-event/unbalanced-args.json
- sample/profiles/trace-event/unbalanced-name.json
- sample/profiles/trace-event/zero-duration-events.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
- src/lib/profile.ts
In #273, I changed `CallTreeProfileBuilder.leaveFrame` to fail hard when you request to leave a frame different from the one at the top of the stack. It turns out we were intentionally doing this for trace event imports, because `args` are part of the frame key, and we want to allow profiles to be imported where the `"B"` and `"E"` events have differing `args` field.
This PR fixes the import code to permissively allow the `"args"` field to not match between the `"B"` and `"E"` fields.
**A note on intentional differences between speedscope and chrome://tracing**
`chrome://tracing` will close whichever frame is at the top when it gets an `"E"` event, regardless of whether the name or the args match. speedscope will ignore the event entirely if the `"name"` field doesn't match, but will warn …
> Fix import of trace event files where B/E events' args don't match

- sample/profiles/trace-event/bex-interaction.json
- sample/profiles/trace-event/event-reordering-name-match.json
- sample/profiles/trace-event/invalid-x-nesting.json
- sample/profiles/trace-event/matching-x.json
- sample/profiles/trace-event/x-events-matching-end.json
- sample/profiles/trace-event/x-events-matching-start.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
The trace event format has a very unfortunate combination of requirements in order to give a best-effort interpretation of a given trace file:
1. Events may be recorded out-of-order by timestamp
2. Events with the *same* timestamp should be processed in the order they were provided in the file. Mostly.
The first requirement is written explicitly [in the spec](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview).
> The events do not have to be in timestamp-sorted order.
The second one isn't explicitly written, but it's implicitly true because otherwise the interpretation of a file is ambiguous. For example, the following file has all events with the same `ts` field, but re-ordering the fields changes the interpretation.
```
[
{ "pid": 0, "tid": 0, "ph": …
```
> Fix trace-event import for many cases where there are 'ts' collisions

- sample/profiles/callgrind/callgrind.example.log
- sample/profiles/callgrind/callgrind.multiple-event-types.log
- sample/profiles/callgrind/callgrind.name-compression.log
- src/import/__snapshots__/callgrind.test.ts.snap
- src/import/callgrind.test.ts
- src/import/callgrind.ts
- src/import/index.ts
Implements import from the [callgrind format](https://www.valgrind.org/docs/manual/cl-format.html).
This comes with a big caveat that the call graph information contained with callgrind formatted files don't uniquely define a flamegraph, so the generated flamegraph is a best-effort guess. Here's the comment from the top of the main file for the callgrind importer with an examplataion:
```
// https://www.valgrind.org/docs/manual/cl-format.html
//
// Larger example files can be found by searching on github:
// https://github.com/search?q=cfn%3D&type=code
//
// Converting callgrind files into flamegraphs is challenging because callgrind
// formatted profiles contain call graphs with weighted nodes and edges, and
// such a weighted call graph does not uniquely define a flamegraph.
//
// …
```
> Callgrind import format support

- README.md
Hello @jlfwong ! 
Thanks to the efforts of @goxberry over in https://github.com/joerick/pyinstrument/pull/160, my profiler pyinstrument now supports speedscope JSON as an output. I thought you might want to mention it in your README.
I couldn't create the wiki page myself, but if you're able to copy paste this as a new page into the wiki that should work:
**Importing from pyinstrument (python)**
```markdown
pyinstrument is a statistical profiler for Python.
pyinstrument has an explicit output format for speedscope (See: https://github.com/joerick/pyinstrument/pull/160).
To profile a Python script and view the output in speedscope, run:
pyinstrument -r speedscope -o profile.speedscope.json your_script.py
Or, you can profile a specific block of code using:
from pyinstrument import Profiler …
```
> Add note about pyinstrument support wiki page

- src/views/application.tsx
Fixes #312 
This turns out not to be very deep: you have to pass an optional second parameter to the [`URL` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) to resolve relative URLs.
```
> new URL('/path/to/file#hashcode').pathnaem
VM252:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL
at <anonymous>:1:1
(anonymous) @ VM252:1
> new URL('/path/to/file#hashcode', 'http://example.com/').pathname
"/path/to/file"
```
> Support relative URLs

- src/views/hovertip.tsx
This changes the HoverTip placement logic to use measurements from the actual DOM node rather than basing everything on the maximum sizes.
This avoids some counter-intuitive behaviour, most importantly situations where the label would overflow off the left side of the screen for no obvious reason.
|Before|After|
|-|-|
|<img width="959" alt="image" src="https://user-images.githubusercontent.com/150329/168766061-f8bfec70-ec7a-48da-bbdf-08373a8065b7.png">|<img width="959" alt="image" src="https://user-images.githubusercontent.com/150329/168766115-951290ba-6dd1-48d8-90b2-161378012b2a.png">|
Fixes #394
Fixes #256
> Improve HoverTip placement logic

- src/lib/profile-search.test.ts
- src/lib/profile-search.ts
- src/views/flamechart-pan-zoom-view.tsx
- src/views/profile-table-view.tsx
- src/views/sandwich-view.tsx
In #297, I re-used the fuzzy matching logic I implemented in #282 for profile selection. Based on feedback from several people in #352, this is surprising behavior.
Upon reflection, this should have been obvious -- I hijacked the Ctrl/Cmd+F browser behaviour, so I should try to replicate the expected behaviour there as closely as possible. Given more patience, I also would've done some user research :)
This PR updates this logic to try to more closely match browser behaviour. This means case-insensitive, exact-substring matching.
I've left the fuzzy matching alone for profile selection since that doesn't attempt to mimic browser behaviour.
The non-fuzzy matching feels slightly odd to me given the filtering behaviour on the sandwich view, but I think consistency across this find UI is …
> Replace fuzzy matching with exact substring matching for finding matching frames

- package-lock.json
- package.json
In #385, I introduced a dependency on the `uint8array-json-parser` npm package, but used a fork because of a typescript error. This was resolved in evanw/uint8array-json-parser#1 and published as part of `uint8array-json-parser@0.0.2`. Let's use the upstream.
This also conveniently fixes a new typechecking error that was preventing deployment. The error looked like this:
```
src/import/utils.ts(2,26): error TS2306: File '\''/Users/jlfwong/code/speedscope/node_modules/uint8array-json-parser/uint8array-json-parser.ts'\'' is not a module.'
```
After updating to the upstream, the problem is fixed.
> Update package.json to use upstream version of uint8array-json-parser

- src/import/__snapshots__/pprof.test.ts.snap
- src/import/pprof.ts
Fixes #415
* Interprets pprof's defaultSampleType as an index into the string table [as documented in the proto](https://github.com/jlfwong/speedscope/blob/0414c2f617742e7fb0cf31a66ac0f77c2f5c0540/src/import/profile.proto#L85), not as an index into the sample types repeated-field. This allows parsing to succeed when the string-table index is not a valid sampleTypes index, which is common on allocation profiles.
* Update the pprof snapshot. This is necessarily because we were previously interpreting an empty defaultSampleType as truthy-but-zero when long.js is present, ie: the first sample-type. But Speedscope-in-the-browser doesn't seem to include long.js, so our tests were disagreeing with in-browser behavior. With this PR, that should be fixed.
> Fix pprof defaultSampleType

- src/lib/text-utils.ts
There was a subtle bug in `trimTextMid` caused by calling substring methods with non-integer values. This happens because `findValueBisect` returns non-integer values, and there was no special handling of this.
The bug results in strings cutting off many of the last few characters in a string, rather than always displaying it when possible.
Before:
After:
Fixes #411
> Fix trimTextMid

- src/import/callgrind.ts
- src/import/instruments.ts
- src/import/papyrus.ts
- src/import/utils.ts
- src/lib/utils.test.ts
The current behavior of splitLines is to eagerly split all the lines and return an array of strings.
This PR improves this by returning an iterator instead, which will emit lines. This lets callers decide how to best use the splitLines function (i.e. lazily enumerate over lines)
Relates to #433
> Improve splitLines: return iterator instead

- src/import/linux-tools-perf.ts
Currently, importing files generated by linux perf tool whose some blocks exceed V8 strings limit can crash the application. This issue is similar to the one in #385.
This PR fixes it by changing parseEvents to work directly with lines instead of chunking lines into blocks first.
Fixes #433
> Fix crash when importing big linux perf tool files

- src/lib/profile.ts
Follow up on this PR #435. 
Currently, it took roughly 22 seconds to load my 1.3GB file. After inspecting the profiler, there's a large chunk of time spending in Frame.getOrInsert. I figure we can reduce the number of invocations by half. It reduces the load time to roughly 18 seconds.I also tested with a smaller file (~350MB), and it show similar gains, about 15-20%
I know this is not a proper way to perform benchmarking, and also I'm clueless about the impact on other file formats/sizes. So I'll leave the judgement to you
> Improve profile builder performance

- scripts/publish-and-deploy.sh
Turns out the `--attach` command was hallucinated by GPT!
> Update publish-and-deploy to remove automated release creation

- .eslintrc.js
- src/import/trace-event.ts
It looks like in #267 (which was 3 years ago!), I accidentally disabled prettier linting altogether 😱
https://github.com/jlfwong/speedscope/pull/267/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5
There's no comment in that PR about this being an intentional thing, so I have to assume this was a dumb mistake.
> Re-enable eslint prettier rule after being accidentally disabled for 3 years

- sample/profiles/trace-event/simple-hermes.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
Profiles that are transformed into the hermes trace event format are guaranteed to have specific arguments that supply metadata that is useful for debugging - namely the filename, line + col number that the function call originated from, with sourcemaps applied. This PR adds specific support for this information to the trace event importer. This means that we can have the Frame name be just the name of the function, since we know all the information we want to be displayed in the UI is captured in the frame info, which makes the traces cleaner to look at.
| Before | After |
|-----|-----|
| <img width="1728" alt="Screenshot 2023-12-26 at 2 40 01 PM" src="https://github.com/jlfwong/speedscope/assets/9957046/f9dff608-5df3-4098-b1f8-91a69185d906"> | <img width="1726" alt="Screenshot …
> Add hermes-specific support for the trace event format

- sample/profiles/trace-event/hermes-multiple-frames.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
Because all args are serialized in the key for hermes profiles, frames were not properly getting grouped since the "parent" property was different. This PR ensures that the frame key is properly constructed from the function name, file name, line + column number.
| Before | After |
| ----- | ----- |
| <img width="1727" alt="Screenshot 2023-12-27 at 2 25 32 PM" src="https://github.com/jlfwong/speedscope/assets/9957046/4ec04653-5a80-4f34-9506-48e0eb415983"> | <img width="1728" alt="Screenshot 2023-12-27 at 2 26 02 PM" src="https://github.com/jlfwong/speedscope/assets/9957046/c3edc447-e8ad-4757-8576-cbb8c27eafe3"> |
| <img width="1720" alt="Screenshot 2023-12-27 at 2 13 37 PM" src="https://github.com/jlfwong/speedscope/assets/9957046/10194aba-8f26-48ca-bf15-06917b44ea99"> | <img width="1728" …
> Improve hermes profile frame keys to better group frames

- sample/profiles/trace-event/simple-with-samples.json
- src/import/trace-event.ts
In the existing code, if `traceEvents` did not have any importable events, the profile would be marked as empty. This was a bug, as the dev Hermes profiles I was testing with had one X event which made the code work. However we do not need to guarantee (and the spec doesn't seem to) any traceEvents being present as long as we have samples and stack frames. 
When I tested a production profile taken from Hermes it did not have any importable events, just a metadata event with a thread name. This PR updates the implementation to iterate over partitioned samples instead of traceEvents so we construct profiles for all thread + process pairs referenced in the samples array.
| Before | After |
| --- | ----- |
| <img width="1454" alt="Screenshot 2024-01-03 at 9 58 56 AM" …
> Partition based on samples instead of traceEvents when importing a sample-based chrome trace

- src/lib/file-format-spec.ts
The spec confused me and I'd like to clarify it. Please check that my understanding is correct!
From the commit message:
> The previous description ("event values will be relative to this startValue") was ambiguous.
> 
> Suppose the profile starts at wall time 1000ms and the first event is at wall time 1003ms.
> 
> The intention is that startValue should be set to 1000 and the "at" value of the event should be set to 1003. The viewer's time axis will start at 0ms and the first event will be displayed at 3ms.
> 
> But the previous description could be incorrectly interpreted as saying that the "at" value of the first event should be set to 3 (the time relative to startValue, as opposed to the absolute wall time).
> 
> Clarify that "relative" is referring to how the viewer displays the …
> Clarify specification of startValue in speedscope file format

- src/views/application.tsx
Steps to reproduce:
1. Open https://www.speedscope.app/
2. Try to import an invalid file such as [invalid.json](https://github.com/jlfwong/speedscope/files/14167326/invalid.json). The page says "Something went wrong. Check the JS console for more details."
3. Now try to import a valid file such as [simple.json](https://github.com/jlfwong/speedscope/files/14167335/simple.json). The page says "Something went wrong. Check the JS console for more details." even though this second file is valid.
Explanation of the fix (copied from the commit message):
> We need to clear the error flag, otherwise once there is an error and we display "Something went wrong" we will keep displaying that forever even when the user imports a valid file.
> Fix bug where import after error continues failing

- .github/workflows/ci.yml
- README-ADMINS.md
- bin/cli.mjs
- package-lock.json
- package.json
See #498
I regenerated all the autogenerated files, but there was an issue with `demangle.wasm.js`: It *also* generated the `module.exports = Module; module.exports.default = Module` lines for some reason, so I manually deleted them.
If you know how to make it only emit ESM exports and leave out the CommonJS exports, I can add that to the makefile.
> Update to working `open`, switch to ESM
