jlfwong/speedscope

- flamechart-view.tsx
- style.ts
> Improve readability and correct bounds of selection & hover rectangles

- flamechart-view.tsx
- index.html
- style.ts
This switches all text to be Source Code Pro instead of Courier for sharper rendering at size 10.
This also changes outline widths to be consistent visual widths on retina and non-retina screens.
> Switch to Source Code Pro, tweak outlines

- flamechart-view.tsx
> Fix position of x axis labels

- package-lock.json
- package.json
- utils.test.ts
- utils.ts
This sets up the first bit of test infrastructure to write and run unit tests on every PR
Related to #14 
Fixes #7
> Integrate jest and add first test file

- math.test.ts
- math.ts
- package-lock.json
- package.json
> Add tests for Vec2, Rect, and AffineTransform

- lru-cache.test.ts
> Add test for LRU cache

- .gitignore
- package-lock.json
- package.json
This adds an integration with https://coveralls.io/ to report on code coverage of tests
> Add test coverage reporting

- import/bg-flamegraph.ts
- import/chrome.ts
- import/firefox.ts
- import/instruments.ts
- import/stackprof.ts
- profile.test.ts
- profile.ts
- value-formatters.test.ts
- value-formatters.ts
> Add tests for Profile and value formatters

- application.tsx
> Add visual indication that the page is a drag target

- src/import/firefox.ts
- src/lib/__snapshots__/profile.test.ts.snap
- src/lib/profile.test.ts
- src/lib/profile.ts
This PR exposed some bugs in the Firefox importer, which is also fixed in this PR.
Fixes #86
> Split CallTreeNodes that are non-contiguous

- src/views/profile-table-view.tsx
- src/views/scrollable-list-view.tsx
> Scroll selected node into sandwich view on mount

- package-lock.json
- package.json
- scripts/generate-file-format-schema-json.js
> Downgrade to TypeScript 2.8.1 to fix JSON schema generation

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- src/README.md
> Add contributor guidelines & documentation

- CHANGELOG.md
- src/gl/canvas-context.ts
- src/gl/graphics.ts
- src/gl/overlay-rectangle-renderer.ts
- src/views/application-container.tsx
- src/views/application.tsx
> Fix rendering bugs when device pixel ratio changes

- CHANGELOG.md
- src/gl/flamechart-renderer.ts
> Fix flamechart bleeding

- src/views/application.tsx
> Alert instead of crash when successfully importing a file containing no profiles

- src/import/index.test.ts
- src/import/index.ts
> Fix crash when importing from stackprof without raw_timestamp_deltas

- sample/profiles/trace-event/too-many-end-events.json
- src/import/__snapshots__/trace-event.test.ts.snap
- src/import/trace-event.test.ts
- src/import/trace-event.ts
> Support import from trace event format event when there are too many "E" events.

- package-lock.json
- package.json
This is the outcome of running `npm audit fix`.  Largely bumping transitive dependencies in the tree.
> Bump parcel and audit fix

- README.md
Add a link to Austin's Speedscope section of the README to Speedscope's README.
> Add link to Austin

- .github/workflows/ci.yml
- .travis.yml
- package-lock.json
- package.json
- src/lib/fuzzy-find.test.ts
Having fewer service dependencies is pretty appealing to me, so let's see if I can drop a dependency on Travis CI in favour of dependening on GitHub Actions instead.
> Switch from Travis CI to GitHub Actions for test runs

- src/lib/text-utils.test.ts
- src/lib/text-utils.ts
Welp, looks like I missed a pretttty important edge case in my test.
Fixes #324
> Fix bug in remapRangesToTrimmedText

- .github/workflows/ci.yml
- src/lib/hash-params.test.ts
> Update a few remaining references to master

- README-ADMINS.md
- scripts/print-changelog-update.sh
- scripts/publish-and-deploy.sh
The publish, deploy, and release process is annoying enough at the moment that I avoid doing it frequently. Let's automate most of it to reduce the friction
> Automate more of the release process
